name: huffobst
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - expat=2.7.4
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.7.4
  - libffi=3.4.4
  - libglib=2.86.3
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.22.1
  - libpng=1.6.54
  - libpq=17.6
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numpy=2.4.2
  - numpy-base=2.4.2
  - openjpeg=2.5.2
  - openssl=3.5.5
  - packaging=25.0
  - pcre2=10.46
  - pillow=11.1.0
  - pip=26.0.1
  - pixman=0.46.4
  - pyparsing=3.2.5
  - pyqt=6.10.2
  - pyqt6-sip=13.11.0
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - qtbase=6.10.2
  - qtdeclarative=6.10.2
  - qtsvg=6.10.2
  - qttools=6.10.2
  - qtwebchannel=6.10.2
  - qtwebsockets=6.10.2
  - setuptools=80.10.2
  - sip=6.15.1
  - six=1.17.0
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tornado=6.5.4
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\jacob\miniconda3\envs\huffobst
